spring:
  datasource:
    url: jdbc:mysql://localhost:3306/afilm?characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: afilm
    password: afilm
    driver-class-name: com.mysql.cj.jdbc.Driver

  ########################################################################################################################################################################
  #spring:
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  profiles:
    include: oauth2
  # H2 Setting Info (H2 Console에 접속하기 위한 설정정보 입력)
  #  h2:
  #    console:
  #      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
  #      path: /h2-console  # H2 Console의 Path
  # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  #  datasource:
  #    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
  #    url: jdbc:h2:~/test  # H2 접속 정보
  #    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
  #    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  ########################################################################################################################################################################
  security:
    user:
      name: user
      password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # JPA 데이터베이스 플랫폼 (InnoDB)
    open-in-view: false
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update  # none, update, create, create-drop, validate

  mvc:
    hiddenmethod:
      filter:
        enabled: true # GET, POST 뿐 만 아니라 PUT, DELETE 등의 메서드도 사용하기 위한 설정

  devtools:
    livereload:
      enabled: true

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
#  thymeleaf:
#    prefix: classpath:templates/
#    check-template-location: true
#    suffix: .html
#    mode: HTML5
#    cache: false